version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: thankful
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    healthcheck:
      test: ['CMD', 'mongo', '--eval', 'db.adminCommand("ping")']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:

