import { Registry, Histogram, Counter } from 'prom-client';
export declare function getRegistry(): Registry;
export declare function counter(config: ConstructorParameters<typeof Counter>[0]): Counter<string>;
export declare function histogram(config: ConstructorParameters<typeof Histogram>[0]): Histogram<string>;
export declare const metrics: {
    seat_lock_acquire_ok_total: Counter<string>;
    seat_lock_acquire_conflict_total: Counter<string>;
    seat_lock_extend_ok_total: Counter<string>;
    seat_lock_release_ok_total: Counter<string>;
    seat_lock_rollback_ok_total: Counter<string>;
    seat_lock_lua_errors_total: Counter<string>;
    seat_lock_redis_timeouts_total: Counter<string>;
    idem_begin_total: Counter<string>;
    idem_begin_conflict_total: Counter<string>;
    idem_inprogress_202_total: Counter<string>;
    idem_commit_total: Counter<string>;
    idem_hit_cached_total: Counter<string>;
    idem_expired_total: Counter<string>;
};
export declare function serializeMetrics(): Promise<string>;
