-- Migration 011: Create non-super test role and grant minimal rights for RLS tests

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'thankful_app') THEN
    CREATE ROLE thankful_app LOGIN PASSWORD 'thankful_app' NOSUPERUSER NOCREATEDB NOCREATEROLE;
  END IF;
END $$;

GRANT USAGE ON SCHEMA identity TO thankful_app;
GRANT USAGE ON SCHEMA venues TO thankful_app;
GRANT USAGE ON SCHEMA orders TO thankful_app;
GRANT USAGE ON SCHEMA payments TO thankful_app;
GRANT USAGE ON SCHEMA inventory TO thankful_app;

DO $$ BEGIN EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA identity TO thankful_app'; END $$;
DO $$ BEGIN EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA venues TO thankful_app'; END $$;
DO $$ BEGIN EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA orders TO thankful_app'; END $$;
DO $$ BEGIN EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA payments TO thankful_app'; END $$;
DO $$ BEGIN EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA inventory TO thankful_app'; END $$;

ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO thankful_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA venues GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO thankful_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA orders GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO thankful_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA payments GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO thankful_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA inventory GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO thankful_app;

INSERT INTO public.schema_migrations (version, checksum) VALUES ('011', 'PLACEHOLDER_CHECKSUM') ON CONFLICT (version) DO NOTHING;


